export const WORDS = [
    // Verbs (Action)
    "lick", "slap", "poke", "wiggle", "moisturize", "explode", "gurgle", "flap", "squirt", "jiggle",
    "stroke", "caress", "nibble", "thrust", "smack", "grind", "ooze", "drip", "squish", "clench",
    "rub", "sniff", "gobble", "swallow", "burp", "fart", "vomit", "sneeze", "twitch", "spasm",
    "gyrate", "undulate", "pulsate", "throb", "quiver", "shudder", "convulse", "secrete", "excrete",
    "defecate", "urinate", "ejaculate", "penetrate", "violate", "molest", "harass", "torture", "mutilate",
    "devour", "consume", "digest", "regurgitate", "ferment", "rot", "decay", "decompose", "fester",
    "spoil", "curdle", "coagulate", "clot", "congeal", "thicken", "harden", "stiffen", "erect",
    "inflate", "expand", "swell", "bloat", "distend", "protrude", "bulge", "sag", "droop",
    "dangle", "flop", "wobble", "shaking", "trembling", "vibrating", "bouncing", "jiggling", "sliding",
    "slipping", "oozing", "dripping", "sucking", "blowing", "biting", "chewing", "gnawing", "crunching",
    "scratch", "scrape", "claw", "tear", "rip", "shred", "crush", "smash", "bash", "batter",
    "bludgeon", "pummel", "beat", "whip", "flog", "spank", "paddle", "cane", "lash", "strike",
    "punch", "kick", "stomp", "trample", "crush", "squeeze", "pinch", "twist", "yank", "pull",
    "drag", "push", "shove", "thrust", "jab", "stab", "slice", "cut", "chop", "dice",
    "mince", "grind", "blend", "puree", "liquefy", "melt", "dissolve", "evaporate", "vaporize",
    "combust", "burn", "scorch", "sear", "char", "roast", "bake", "fry", "boil", "steam",
    "poach", "simmer", "stew", "braise", "grill", "barbecue", "smoke", "cure", "salt", "pickle",
    "marinate", "season", "spice", "flavor", "taste", "smell", "scent", "sniff", "inhale", "exhale",
    "breathe", "gasp", "pant", "wheeze", "choke", "cough", "gag", "retch", "heave", "spit",
    "drool", "slobber", "dribble", "leak", "seep", "drain", "flow", "gush", "spurt", "spray",
    "hump", "mount", "ride", "straddle", "stroke", "rub", "massage", "knead", "squeeze", "fondle",
    "grope", "touch", "feel", "handle", "manipulate", "manhandle", "abuse", "misuse", "exploit",
    "cheat", "deceive", "trick", "fool", "scam", "con", "dupe", "hoodwink", "bamboozle",
    "confuse", "befuddle", "perplex", "puzzle", "baffle", "mystify", "bewilder", "disorient", "distract",
    "disturb", "disrupt", "interrupt", "interfere", "meddle", "tamper", "tinker", "fiddle", "toy",

    // Nouns (Objects/Concepts)
    "spatula", "moisture", "clown", "sausage", "explosion", "mother", "taxes", "diapers", "bacon",
    "yeast", "fungus", "mold", "slime", "mucus", "phlegm", "snot", "scab", "pus", "boil",
    "blister", "wart", "tumor", "cyst", "polyp", "hemorrhoid", "fistula", "ulcer", "abscess",
    "carbuncle", "pimple", "zit", "acne", "blackhead", "whitehead", "rash", "hives", "eczema",
    "psoriasis", "dandruff", "lice", "maggots", "worms", "roaches", "rats", "mice", "vermin",
    "sewage", "sludge", "scum", "trash", "garbage", "rubbish", "refuse", "waste", "filth",
    "dirt", "grime", "muck", "mud", "mire", "bog", "swamp", "marsh", "cesspool", "latrine",
    "toilet", "urinal", "bidet", "commode", "bedpan", "chamberpot", "outhouse", "dungeon", "torture",
    "shackles", "chains", "whips", "branding", "iron", "spikes", "nails", "screws", "blades",
    "knives", "swords", "axes", "saws", "drills", "hammers", "pliers", "wrenches", "screwdrivers",
    "clamps", "vises", "chainsaws", "machetes", "cleavers", "scalpels", "needles", "syringes", "catheters",
    "enemas", "suppositories", "tampons", "pads", "diapers", "condoms", "lubricant", "lotion", "ointment",
    "salve", "balm", "cream", "gel", "paste", "wax", "grease", "oil", "fat", "lard",
    "butter", "margarine", "shortening", "tallow", "suet", "drippings", "gravy", "sauce", "juice",
    "fluid", "liquid", "secretion", "excretion", "discharge", "effluent", "emission", "output", "product",
    "byproduct", "waste", "residue", "remains", "leavings", "scraps", "crumbs", "dregs", "sediment",
    "sludge", "silt", "ooze", "goop", "gunk", "muck", "mire", "slush", "slurry",
    "puddle", "pool", "spill", "stain", "soak", "drench", "sop", "sponge", "wipe",
    "rag", "cloth", "towel", "tissue", "paper", "cardboard", "plastic", "rubber", "latex",
    "leather", "vinyl", "nylon", "polyester", "silk", "satin", "velvet", "wool", "cotton",
    "fur", "feathers", "hair", "skin", "hide", "pelt", "fleece", "scales", "shell",
    "bone", "horn", "antler", "tusk", "claw", "nail", "tooth", "beak", "bill",
    "snout", "muzzle", "nose", "trunk", "tail", "fin", "flipper", "wing", "leg",
    "foot", "paw", "hoof", "hand", "finger", "thumb", "toe", "eye", "ear",
    "mouth", "tongue", "lip", "gum", "throat", "neck", "shoulder", "arm", "elbow",
    "wrist", "chest", "breast", "nipple", "belly", "navel", "back", "spine", "hip",
    "waist", "butt", "groin", "thigh", "knee", "shin", "calf", "ankle", "heel",

    // Adjectives
    "moist", "soggy", "damp", "wet", "sticky", "clammy", "slimy", "greasy", "oily",
    "crusty", "crunchy", "flaky", "dusty", "powdery", "gritty", "sandy", "coarse", "rough",
    "smooth", "slick", "slippery", "velvety", "silky", "soft", "hard", "stiff", "rigid",
    "limp", "flaccid", "saggy", "droopy", "loose", "tight", "firm", "taught", "tense",
    "bloated", "swollen", "inflamed", "infected", "diseased", "rotten", "spoiled", "rancid", "putrid",
    "foul", "nasty", "gross", "disgusting", "revolting", "repulsive", "vile", "wicked", "evil",
    "sinister", "malevolent", "malicious", "cruel", "brutal", "savage", "barbaric", "primitive", "ancient",
    "modern", "futuristic", "alien", "strange", "bizarre", "weird", "freaky", "kinky", "fetish",
    "taboo", "forbidden", "illegal", "criminal", "corrupt", "depraved", "perverted", "immoral", "unethical",
    "sinful", "blasphemous", "sacrilegious", "heretical", "godless", "faithless", "hopeless", "despairing", "depressed",
    "anxious", "nervous", "scared", "afraid", "terrified", "petrified", "horrified", "shocked", "stunned",
    "amazed", "astonished", "surprised", "confused", "bewildered", "perplexed", "puzzled", "baffled", "lost",
    "lonely", "alone", "isolated", "abandoned", "rejected", "unwanted", "unloved", "hated", "despised",
    "loathed", "detested", "abhorred", "scorned", "mocked", "ridiculed", "insulted", "offended", "hurt",
    "wounded", "injured", "damaged", "broken", "shattered", "destroyed", "ruined", "wrecked", "demolished",
    "obliterated", "annihilated", "extinct", "dead", "dying", "lifeless", "inanimate", "hollow", "empty",
    "vacant", "blank", "numb", "cold", "freezing", "frozen", "icy", "chilly", "cool",
    "warm", "hot", "burning", "scorching", "searing", "blazing", "fiery", "flaming", "glowing",
    "bright", "shiny", "sparkling", "glittering", "shimmering", "dull", "dim", "dark", "gloomy",
    "shadowy", "murky", "cloudy", "foggy", "misty", "hazy", "blurry", "fuzzy", "clear",
    "transparent", "translucent", "opaque", "solid", "liquid", "gaseous", "vaporous", "ethereal", "ghostly",
    "spectral", "haunted", "possessed", "cursed", "jinxed", "lucky", "unlucky", "fortunate", "unfortunate",

    // Body Parts (Anatomy)
    "elbow", "knee", "toe", "finger", "thumb", "knuckle", "wrist", "ankle", "heel",
    "sole", "arch", "shin", "calf", "thigh", "buttock", "hip", "waist", "navel",
    "belly", "chest", "nipple", "breast", "shoulder", "neck", "chin", "cheek", "nose",
    "ear", "eye", "eyebrow", "eyelash", "hair", "scalp", "tongue", "tooth", "gum",
    "lip", "throat", "spine", "rib", "pelvis", "bone", "muscle", "tendon", "ligament",
    "nerve", "vein", "artery", "heart", "lung", "stomach", "liver", "kidney", "bladder",
    "intestine", "colon", "rectum", "anus", "sphincter", "genitals", "flesh", "skin", "blood",
    "sweat", "tears", "saliva", "urine", "feces", "semen", "vomit", "bile", "phlegm",
    "brain", "skull", "jaw", "mandible", "clavicle", "scapula", "humerus", "radius", "ulna",
    "femur", "patella", "tibia", "fibula", "vertebra", "sacrum", "coccyx", "cranium", "sternum",
    "cartilage", "marrow", "plasma", "platelet", "cell", "tissue", "organ", "gland", "hormone",
    "enzyme", "protein", "vitamin", "mineral", "nutrient", "fat", "sugar", "salt", "acid",
    "base", "alkali", "toxin", "poison", "venom", "antidote", "cure", "remedy", "medicine",
    "drug", "pill", "tablet", "capsule", "syringe", "injection", "vaccine", "antibiotic", "steroid",
    "narcotic", "stimulant", "sedative", "hallucinogen", "anesthetic", "painkiller", "opiate", "addict", "junkie",

    // People/Roles
    "governor", "senator", "president", "dictator", "king", "queen", "prince", "princess", "duke",
    "duchess", "baron", "baroness", "count", "countess", "knight", "squire", "peasant", "serf",
    "slave", "master", "mistress", "servant", "maid", "butler", "cook", "chef", "waiter",
    "waitress", "bartender", "customer", "client", "guest", "host", "hostess", "visitor", "tourist",
    "stranger", "foreigner", "alien", "immigrant", "refugee", "exile", "outcast", "hermit", "monk",
    "nun", "priest", "rabbi", "imam", "guru", "shaman", "witch", "wizard", "sorcerer",
    "sorceress", "mage", "warlock", "necromancer", "vampire", "werewolf", "zombie", "ghost", "spirit",
    "demon", "devil", "angel", "god", "goddess", "deity", "idol", "icon", "hero",
    "villain", "monster", "beast", "creature", "mutant", "freak", "weirdo", "creep", "pervert",
    "deviant", "criminal", "felon", "convict", "prisoner", "inmate", "jailbird", "thief", "robber",
    "burglar", "mugger", "killer", "murderer", "assassin", "sniper", "soldier", "warrior", "fighter",
    "mercenary", "spy", "agent", "detective", "cop", "police", "officer", "sheriff", "deputy",
    "judge", "jury", "lawyer", "attorney", "prosecutor", "defendant", "witness", "victim", "suspect",
    "doctor", "nurse", "surgeon", "dentist", "patient", "sick", "ill", "invalid", "cripple",
    "lunatic", "maniac", "psycho", "sociopath", "psychopath", "narcissist", "sadist", "masochist", "fetishist",

    // Food
    "smoothie", "milkshake", "juice", "soda", "water", "milk", "coffee", "tea", "beer",
    "wine", "liquor", "vodka", "whiskey", "rum", "gin", "tequila", "brandy", "champagne",
    "cocktail", "mocktail", "slushie", "syrup", "honey", "jam", "jelly", "marmalade", "butter",
    "oil", "vinegar", "sauce", "ketchup", "mustard", "mayonnaise", "relish", "salsa", "guacamole",
    "hummus", "dip", "dressing", "gravy", "soup", "stew", "chili", "curry", "noodles",
    "pasta", "rice", "beans", "peas", "lentils", "corn", "potatoes", "carrots", "broccoli",
    "spinach", "lettuce", "kale", "cabbage", "onions", "garlic", "peppers", "tomatoes", "cucumbers",
    "pickles", "olives", "mushrooms", "cheese", "yogurt", "cream", "ice cream", "cake", "pie",
    "cookies", "brownies", "donuts", "muffins", "bagels", "bread", "toast", "pancakes", "waffles",
    "biscuit", "scone", "croissant", "danish", "strudel", "tart", "custard", "pudding", "gelatin",
    "mousse", "candy", "chocolate", "caramel", "toffee", "fudge", "truffle", "bonbon", "lollipop",
    "gum", "mint", "taffy", "marshmallow", "popcorn", "chips", "pretzels", "crackers", "nuts",
    "peanuts", "almonds", "cashews", "wilnuts", "pecans", "pistachios", "hazelnuts", "macadamias", "seeds",
    "sunflower", "pumpkin", "sesame", "poppy", "flax", "chia", "hemp", "granola", "oats",
    "wheat", "barley", "rye", "cornmeal", "flour", "yeast", "dough", "batter", "crust",
    "meat", "beef", "pork", "lamb", "veal", "venison", "chicken", "turkey", "duck",
    "goose", "quail", "pheasant", "fish", "salmon", "tuna", "cod", "halibut", "trout",
    "sardine", "anchovy", "shrimp", "prawn", "crab", "lobster", "crayfish", "clam", "mussel",
    "oyster", "scallop", "squid", "octopus", "snail", "frog", "turtle", "alligator", "snake",

    // Animals
    "cat", "dog", "mouse", "rat", "hamster", "guinea pig", "rabbit", "squirrel", "chipmunk",
    "beaver", "porcupine", "skunk", "raccoon", "opossum", "mole", "bat", "fox", "wolf",
    "coyote", "bear", "lion", "tiger", "leopard", "jaguar", "cheetah", "panther", "lynx",
    "bobcat", "cougar", "mountain lion", "wildcat", "domestic cat", "feral cat", "kitten", "puppy", "cub",
    "calf", "foal", "colt", "filly", "lamb", "kid", "piglet", "chick", "duckling",
    "gosling", "cygnet", "fawn", "joey", "tadpole", "caterpillar", "larva", "pupa", "nymph",
    "dragonfly", "wasp", "hornet", "bee", "ant", "termite", "beetle", "cockroach", "cricket",
    "grasshopper", "locust", "mantis", "cicada", "flea", "louse", "mite", "tick", "spider",
    "scorpion", "centipede", "millipede", "worm", "slug", "snail", "leech", "jellyfish", "anemone",
    "coral", "sponge", "starfish", "urchin", "cucumber", "dollar", "shell", "conch", "nautilus",
    "squid", "octopus", "cuttlefish", "shark", "ray", "skate", "eel", "whale", "dolphin",
    "porpoise", "seal", "lion", "walrus", "manatee", "dugong", "penguin", "puffing", "gull",
    "albatross", "pelican", "cormorant", "stork", "heron", "egret", "flamingo", "crane", "swan",
    "goose", "duck", "eagle", "hawk", "falcon", "owl", "vulture", "parrot", "cockatoo",

    // Abstract
    "failure", "disappointment", "regret", "shame", "guilt", "fear", "anxiety", "panic", "terror",
    "horror", "dread", "despair", "misery", "suffering", "pain", "agony", "torture", "torment",
    "anguish", "grief", "sorrow", "sadness", "depression", "melancholy", "loneliness", "isolation", "rejection",
    "abandonment", "betrayal", "treachery", "deceit", "lies", "falsehood", "dishonesty", "fraud", "corruption",
    "injustice", "oppression", "tyranny", "dictatorship", "slavery", "war", "violence", "conflict", "battle",
    "fight", "struggle", "combat", "destruction", "devastation", "ruin", "collapse", "downfall", "end",
    "death", "dying", "killed", "murdered", "slaughtered", "massacred", "executed", "assassinated", "suicide",
    "homicide", "genocide", "warfare", "casualty", "victim", "martyr", "saint", "sinner", "redemption",
    "salvation", "damnation", "hell", "heaven", "purgatory", "limbo", "afterlife", "eternity", "infinity",
    "void", "abyss", "nothingness", "chaos", "order", "law", "rule", "power", "control",
    "authority", "command", "dominion", "empire", "kingdom", "realm", "domain", "territory", "border",
    "boundary", "limit", "edge", "fringe", "margin", "periphery", "center", "core", "heart",
    "soul", "spirit", "mind", "consciousness", "awareness", "perception", "reality", "illusion", "dream",
    "nightmare", "fantasy", "fiction", "myth", "legend", "fable", "tale", "story", "narrative",

    // Random Funny / Slang / Brainrot
    "bamboozle", "shenanigans", "tomfoolery", "malarkey", "hogwash", "balderdash", "poppycock", "gibberish", "nonsense",
    "gobbledygook", "flapdoodle", "claptrap", "drivel", "twaddle", "bosh", "pish-posh", "fiddlesticks", "humbug",
    "scuttlebutt", "codswallop", "kerfuffle", "brouhaha", "hullabaloo", "commotion", "ruckus", "donnybrook", "fracas",
    "melee", "scuffle", "tussle", "brawl", "skirmish", "clash", "confrontation", "encounter", "incident",
    "accident", "mishap", "blunder", "mistake", "error", "fault", "flaw", "defect", "imperfection",
    "yeet", "yoink", "glizzy", "sus", "cringe", "based", "chad", "simp", "karen",
    "zoomer", "boomer", "doomer", "bloomer", "coomer", "gooner", "mewing", "skibidi", "gyatt",
    "rizz", "fanum", "tax", "ohio", "sigma", "alpha", "beta", "omega", "grindset",
    "hustle", "gaslight", "gatekeep", "girlboss", "mansplain", "woke", "cancelled", "triggered", "snowflake",
    "libtard", "maga", "covfefe", "bigly", "yuge", "fake", "news", "hoax", "conspiracy",
    "illuminati", "aliens", "ufo", "bigfoot", "yeti", "nessie", "chupacabra", "cryptid", "monster",
    "balls", "nuts", "shaft", "tip", "taint", "gooch", "chode", "boner", "wood",
    "stiffy", "hardon", "erection", "climax", "orgasm", "cum", "jizz", "spunk", "load",
    "nut", "seed", "juice", "cream", "sauce", "squirt", "gush", "flow", "drip",
    "wet", "moist", "damp", "soggy", "soaked", "drenched", "flooded", "overflowing", "spilling",
    "leaking", "dripping", "oozing", "seeping", "bleeding", "draining", "emptying", "pouring", "raining"
];
